name: "Webhook Event example"

on:
  repository_dispatch:
    types:
      - custom_webhook

jobs:
  respond-to-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Display webhook event type
        run: echo "Event type: ${{ github.event.action }}"
